// examples/svelte/src/App.svelte
<script lang="ts">
    // Side-effect import: registers <zulip-chat> as a Custom Element.
    // Svelte's compiler treats unknown tags as plain DOM, so the element
    // renders natively with zero extra config — no `isCustomElement`
    // flag, no wrapper component.
    import "zulip-embed/chat";
</script>

<main class="wrap">
    <h1>Zulip Embed — Svelte 5 (Vite) example</h1>
    <p class="lead">
        This page renders <code>&lt;zulip-chat demo&gt;</code> from a Svelte 5 component. Demo
        mode routes through an in-memory transport with seeded messages — no server needed.
    </p>

    <zulip-chat
        demo
        channel="general"
        topic="welcome"
        theme="light"
        mode="inline"
        brand-name="Demo Chat"
    ></zulip-chat>

    <footer>
        Drop <code>demo</code> and add <code>server</code>, <code>email</code>, and
        <code>api-key</code> for live mode.
    </footer>
</main>

<style>
    .wrap {
        max-width: 720px;
        margin: 0 auto;
        padding: 32px 20px 56px;
    }

    h1 {
        margin: 0 0 8px;
        font-size: 22px;
        font-weight: 700;
    }

    p.lead {
        margin: 0 0 24px;
        color: #4b5563;
        font-size: 14px;
        line-height: 1.55;
    }

    p.lead code,
    footer code {
        background: #eef1f5;
        padding: 1px 5px;
        border-radius: 4px;
        font-size: 13px;
    }

    zulip-chat {
        width: 100%;
        height: 560px;
        display: block;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 10px 30px -12px rgba(17, 24, 39, 0.25);
    }

    footer {
        margin-top: 20px;
        font-size: 12px;
        color: #6b7280;
        text-align: center;
    }
</style>

// examples/react/src/App.tsx
// Minimal React integration: import <ZulipChat> from `zulip-embed-react`
// and drop it anywhere. The wrapper side-effect-registers the
// underlying <zulip-chat> Custom Element on import, so you don't also
// need `import "zulip-embed"`.
//
// `demo` disables every network path and routes through an in-memory
// seeded transport with an echo bot. Remove it and pass
// `server` / `email` / `apiKey` for a live connection.

import {ZulipChat} from "zulip-embed-react";

export function App() {
    return (
        <main
            style={{
                maxWidth: 720,
                margin: "0 auto",
                padding: "32px 20px 56px",
            }}
        >
            <h1 style={{fontSize: 22, margin: "0 0 8px"}}>
                Zulip Embed — React (Vite) example
            </h1>
            <p
                style={{
                    margin: "0 0 24px",
                    color: "#4b5563",
                    fontSize: 14,
                    lineHeight: 1.55,
                }}
            >
                This page renders <code>&lt;ZulipChat demo&gt;</code> from{" "}
                <code>zulip-embed-react</code>. Demo mode routes through an in-memory
                transport with seeded messages — no server needed.
            </p>

            <ZulipChat
                demo
                channel="general"
                topic="welcome"
                theme="light"
                mode="inline"
                brandName="Demo Chat"
                style={{
                    display: "block",
                    width: "100%",
                    height: 560,
                    borderRadius: 12,
                    overflow: "hidden",
                    boxShadow: "0 10px 30px -12px rgba(17, 24, 39, 0.25)",
                }}
                onMessage={(detail) => {
                    // Typed event — detail.message has the full Zulip message shape.
                    console.log("message:", detail.message);
                }}
                onConnectionChange={(detail) => {
                    console.log("connection:", detail.status);
                }}
            />

            <p
                style={{
                    marginTop: 20,
                    textAlign: "center",
                    fontSize: 12,
                    color: "#6b7280",
                }}
            >
                Drop <code>demo</code> and add <code>server</code>,{" "}
                <code>email</code>, and <code>apiKey</code> for live mode.
            </p>
        </main>
    );
}
